### ISSUE TITLE
Can you give an instruction to run your code?

### ISSUE THREAD

**Issue by ReinaFeng** [TheCodez/pytorch-GoogLeNet-FCN#1]

**Comment by TheCodez** [comment]
#### Cityscapes:
If you want to train from scratch you have to extract `leftImg8bit_trainvaltest.zip` and `gtFine_trainvaltest.zip` into `data/cityscapes` (if you want to train on fine and coarse you have to download and unzip `leftImg8bit_trainextra.zip` and `gtCoarse.zip` as well).

Then call the following command from the root directory if you want to train on fine only:
`python3 train.py --lr 1e-10 --batch-size 1 --freeze-bn --epochs 150`

If you want to train on fine and coarse extra use:
`python3 train.py --lr 3.3e-10 --batch-size 2 --epochs 200 --freeze-bn --include-coarse`

#### VOC (SBD augmented)
For VOC the dataset is donwloaded automatically when using the `--download` parameter.

`python3 train_sbd.py --lr 1e-10 --batch-size 1 --freeze-bn --download`

#### Pretrained model
If you want to use a pretrained model only (note those are still WIP) you could use torch hub for that:

```python
import torch.hub as hub
model = hub.load('TheCodez/pytorch-GoogLeNet-FCN', 'googlenet_fcn', pretrained='cityscapes')

```
or

```python
import torch.hub as hub
model = hub.load('TheCodez/pytorch-GoogLeNet-FCN', 'googlenet_fcn', pretrained='voc_aug')
```


Let me know if all works well.
